Repository apache/maven-build-cache-extension, pull requests merged in 2023-11, with the labels that each got.

#105 [PR-105] Regression : direct input files located in target (usually s…
  src/main/java/org/apache/maven/buildcache/checksum/exclude/ExclusionResolver.java
  src/test/projects/include-exclude/assembly-sources.xml
  src/test/projects/include-exclude/pom.xml
Labels: no-changelog

#106 Fix How To XSD links
  src/site/markdown/how-to.md
Labels: documentation

#109 Upgrade Maven core versions used in for GHA and in pom
  .github/workflows/maven-verify-3.9.x.yml
  .github/workflows/maven-verify.yml
  pom.xml
Labels: maintenance

#111 Copy edits
  src/site/markdown/index.md
Labels: no-changelog

#110 [MBUILDCACHE-74] Clean local cache for any artifact
  pom.xml
  src/main/java/org/apache/maven/buildcache/CacheControllerImpl.java
  src/test/java/org/apache/maven/buildcache/its/Issue74Test.java
  src/test/projects/mbuildcache-74-clean-cache-any-artifact/.mvn/extensions.xml
  src/test/projects/mbuildcache-74-clean-cache-any-artifact/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-74-clean-cache-any-artifact/pom.xml
Labels: bug

#113 [MBUILDCACHE-75] Upgrade to parent 41
  pom.xml
Labels: maintenance

#114 revert some non needed changes from https://github.com/apache/maven-build-cache-extension/pull/110
  pom.xml
Labels: no-changelog

#115 Fix javadoc:jar generation and add it in the verify goals
  .github/workflows/maven-verify-3.9.x.yml
  .github/workflows/maven-verify.yml
  src/main/mdo/build-cache-config.mdo
Labels: maintenance
