Repository apache/maven-build-cache-extension, pull requests merged in 2023-02, with the labels that each got.

#37 [MBUILDCACHE-37] Allow disabled-by-default configuration to be enabled on the CLI
  src/main/java/org/apache/maven/buildcache/xml/CacheConfigImpl.java
  src/site/markdown/usage.md
Labels: enhancement

#41 use our shared GHA build, add dependabot and release drafter
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/maven-verify.yml
  .github/workflows/maven.yml
  .github/workflows/release-drafter.yml
  pom.xml
  src/main/java/org/apache/maven/buildcache/BuildCacheMojosExecutionStrategy.java
  src/main/java/org/apache/maven/buildcache/xml/XmlService.java
  src/test/java/org/apache/maven/buildcache/BuildCacheMojosExecutionStrategyTest.java
  src/test/java/org/apache/maven/buildcache/its/RemoteCacheDavTest.java
  src/test/resources/logback.xml
Labels: maintenance

#38 docs: fix build-cache dir name in getting-started
  src/site/markdown/getting-started.md
Labels: documentation
