Repository apache/maven-build-cache-extension, pull requests merged in 2023-04, with the labels that each got.

#51 [MBUILDCACHE-48] - Add possibility to disable caching per module in a multi-module project
  src/main/java/org/apache/maven/buildcache/BuildCacheMojosExecutionStrategy.java
  src/main/java/org/apache/maven/buildcache/CacheControllerImpl.java
  src/main/java/org/apache/maven/buildcache/checksum/MavenProjectInput.java
  src/test/java/org/apache/maven/buildcache/its/PerModuleFlagsTest.java
  src/test/projects/per-module-flags/.mvn/extensions.xml
  src/test/projects/per-module-flags/.mvn/maven-build-cache-config.xml
  src/test/projects/per-module-flags/module1/pom.xml
  src/test/projects/per-module-flags/module1/src/main/java/org/apache/maven/buildcache/Test1.java
  src/test/projects/per-module-flags/module2/pom.xml
  src/test/projects/per-module-flags/module2/src/main/java/org/apache/maven/buildcache/Test2.java
  src/test/projects/per-module-flags/module3/pom.xml
  src/test/projects/per-module-flags/module3/src/main/java/org/apache/maven/buildcache/Test3.java
  src/test/projects/per-module-flags/pom.xml
Labels: enhancement

#70 Filter the project version into the getting started guide
  src/site/markdown/getting-started.md.vm
Labels: documentation

#74 [MBUILDCACHE-57] Configure remote url/remote server id with command line property
  src/main/java/org/apache/maven/buildcache/xml/CacheConfigImpl.java
  src/site/markdown/parameters.md
  src/test/java/org/apache/maven/buildcache/its/RemoteCacheDavTest.java
Labels: enhancement

#75 add some log when saving file locally as nothing is displayed if this has been done or not
  src/main/java/org/apache/maven/buildcache/LocalCacheRepositoryImpl.java
Labels: enhancement

#78 use junit bom
  pom.xml
Labels: maintenance
