Repository apache/maven-build-cache-extension, pull requests merged in 2024-07, with the labels that each got.

#146 [MBUILDCACHE-87] - Checksum should consider plugin dependencies
  src/main/java/org/apache/maven/buildcache/CacheDiff.java
  src/main/java/org/apache/maven/buildcache/checksum/DigestUtils.java
  src/main/java/org/apache/maven/buildcache/checksum/MavenProjectInput.java
  src/main/java/org/apache/maven/buildcache/xml/CacheConfig.java
  src/main/java/org/apache/maven/buildcache/xml/CacheConfigImpl.java
  src/main/mdo/build-cache-config.mdo
  src/site/markdown/how-to.md
  src/site/resources/maven-build-cache-config.xml
  src/test/java/org/apache/maven/buildcache/its/Issue87Test.java
  src/test/projects/mbuildcache-87/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-87/external/pom.xml
  src/test/projects/mbuildcache-87/top/.mvn/extensions.xml
  src/test/projects/mbuildcache-87/top/module1/pom.xml
  src/test/projects/mbuildcache-87/top/module1/src/main/resources/org/apache/maven/buildcache/test.properties
  src/test/projects/mbuildcache-87/top/module2/pom.xml
  src/test/projects/mbuildcache-87/top/module2/src/main/java/org/apache/maven/buildcache/Test2.java
  src/test/projects/mbuildcache-87/top/pom.xml
Labels: enhancement

#161 [MBUILDCACHE-99] Project checksum fails to identify moved files in certain cases
  src/main/java/org/apache/maven/buildcache/checksum/DigestUtils.java
  src/main/java/org/apache/maven/buildcache/checksum/MavenProjectInput.java
  src/test/java/org/apache/maven/buildcache/its/Issue99Test.java
  src/test/projects/mbuildcache-99/.mvn/extensions.xml
  src/test/projects/mbuildcache-99/pom.xml
  src/test/projects/mbuildcache-99/test-module/pom.xml
  src/test/projects/mbuildcache-99/test-module/src/main/resources/test.properties
Labels: bug

#165 [MBUILDCACHE-100] - Fix exclusion example in docs
  src/site/markdown/performance.md
Labels: documentation
