Repository apache/maven-build-cache-extension, pull requests merged in 2024-05, with the labels that each got.

#104 [MBUILDCACHE-86] bugfix / enhancements restoration of outputs on disk
  src/main/java/org/apache/maven/buildcache/CacheControllerImpl.java
  src/main/java/org/apache/maven/buildcache/CacheUtils.java
  src/main/java/org/apache/maven/buildcache/artifact/OutputType.java
  src/main/java/org/apache/maven/buildcache/artifact/RestoredArtifact.java
  src/main/java/org/apache/maven/buildcache/checksum/MavenProjectInput.java
  src/main/java/org/apache/maven/buildcache/xml/CacheConfig.java
  src/main/java/org/apache/maven/buildcache/xml/CacheConfigImpl.java
  src/main/mdo/build-cache-build.mdo
  src/main/mdo/build-cache-config.mdo
  src/site/markdown/parameters.md
  src/test/java/org/apache/maven/buildcache/its/IncrementalRestoreTest.java
  src/test/java/org/apache/maven/buildcache/its/Issue67Test.java
  src/test/projects/mbuildcache-incremental/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-incremental/pom.xml
  src/test/projects/mbuildcache-incremental/src/main/resources/extra-readme-1.md
  src/test/projects/mbuildcache-incremental/src/main/resources/extra-readme-2.md
  src/test/projects/mbuildcache-incremental/src/main/resources/other-readme-1.md
Labels: bug

#150 Fix typo in maven-build-cache-config.xml
  src/site/resources/maven-build-cache-config.xml
Labels: documentation

#152 remove wrong tag in pom and use last maven 3 version for ITs
  pom.xml
Labels: maintenance
