Repository apache/maven-build-cache-extension, pull requests merged in 2025-04, with the labels that each got.

#201 [MBUILDCACHE-111] Documentation uses build-cache-config 1.0.0 XML schema instead of 1.2.0 schema
  pom.xml
  src/site/markdown/how-to.md
  src/site/resources/maven-build-cache-config.xml
  src/test/projects/build-extension/.mvn/maven-build-cache-config.xml
  src/test/projects/core-extension/.mvn/maven-build-cache-config.xml
  src/test/projects/duplicate-goals/.mvn/maven-build-cache-config.xml
  src/test/projects/forked-executions-core-extension-remote/.mvn/maven-build-cache-config.xml
  src/test/projects/forked-executions-core-extension/.mvn/maven-build-cache-config.xml
  src/test/projects/include-exclude/.mvn/maven-build-cache-config.xml
  src/test/projects/mandatory-clean/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-21/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-56-mojo-parameter-as-method/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-67/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-74-clean-cache-any-artifact/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-76/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-87/.mvn/maven-build-cache-config.xml
  src/test/projects/mbuildcache-incremental/.mvn/maven-build-cache-config.xml
  src/test/projects/per-module-flags/.mvn/maven-build-cache-config.xml
  src/test/projects/remote-cache-dav/.mvn/maven-build-cache-config.xml
  src/test/resources/org/apache/maven/buildcache/xml/build-cache-build-instance.xml
  src/test/resources/org/apache/maven/buildcache/xml/build-cache-config-instance.xml
  src/test/resources/org/apache/maven/buildcache/xml/build-cache-diff-instance.xml
  src/test/resources/org/apache/maven/buildcache/xml/build-cache-report-instance.xml
Labels: documentation

#204 build against 4.0.0-rc-3
  .github/workflows/maven-verify-3.9.x.yml
  .github/workflows/maven-verify.yml
Labels: maintenance

#207 [MBUILDCACHE-123] do not set projectExecutions if cacheState is disabled
  pom.xml
  src/main/java/org/apache/maven/buildcache/MojoParametersListener.java
Labels: bug

#205 [MBUILDCACHE-113] java.security.AccessController in java.security has been deprecated and marked for removal
  src/main/java/org/apache/maven/buildcache/hash/CloseableBuffer.java
Labels: maintenance
